In [1]:
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')

In [2]:
df = pd.read_excel('data/tracking.xlsx')
# To date time 
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df['hour'] = df['Timestamp'].dt.hour
df['day'] = df['Timestamp'].dt.day
df['month'] = df['Timestamp'].dt.month

                  Timestamp     Activity Comment
0   2024-01-10 22:17:59.554  Go to sleep     NaN
1   2024-01-10 23:14:09.490      Wake up     NaN
2   2024-01-10 23:14:39.128  Bottle Feed     NaN
3   2024-01-10 23:25:58.353    Wet nappy     NaN
4   2024-01-10 23:32:52.000  Go to sleep     NaN
..                      ...          ...     ...
98  2024-01-13 17:53:41.169      Wake up     NaN
99  2024-01-13 17:54:57.881  Bottle Feed     NaN
100 2024-01-13 18:22:35.078    Wet nappy     NaN
101 2024-01-13 18:34:22.545  Go to sleep     NaN
102 2024-01-13 19:57:36.465      Wake up     NaN

[103 rows x 3 columns]